### ISSUE TITLE
Score is being set to 0

### ISSUE THREAD

**Issue by acmello** [acmello/social-snakes#7]
Not sure about the situation, but sometimes the score value is being overwrited. It may happen when the user cancel the game, get back to the start screen and them get back to the game. But it needs to be tested.

**Comment by crisstanza** [comment]
Apparently it's not happening anymore.

**Comment by crisstanza** [comment]
This happens when the user starts scoring points before Facebook api call return his current score. Score value 0 will not be recorded, but any value greater than 0 will post the value.

**Comment by crisstanza** [comment]
Fixed! Now the current score of the playing player will not be sent unless the current score stored on Facebook be known, thus, only a higher score will be sent.
